feat: added onPaste support
AnkiPro/react-native-rich-text pull request #3
Opened 2023-05-24 14:03 UTC by kornasevich

2023-05-26 05:26 UTC, tokkozhin requested changes

2023-05-26 05:26 UTC, tokkozhin commented on src/html/scripts/RNEditor.ts
> +        handlePaste: ()=> {
can you move out to a separate method

2023-05-31 07:40 UTC, gontovnik requested changes
See Daniel's comments

2023-06-09 10:37 UTC, tokkozhin approved these changes

2023-06-09 10:37 UTC, merged